name: integrations

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04

    name: Integrations

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^9.0" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute integration tests
        env:
          GIPHY_KEY: ${{ secrets.GIPHY_KEY }}
          IP_API_KEY: ${{ secrets.IP_API_KEY }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
        run: vendor/bin/phpunit --testsuite integration
